version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:23.1.0
    environment:
          KEY_PASSPHRASE: ${{ secrets.KEY_PASSPHRASE }}
    steps:
      - checkout
      - run:
          name: Install Bun
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> $BASH_ENV
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Install dependencies and build project
          command: |
            cd backend
            bun install
            cd ..
            cd frontend
            bun install
            bun run build
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud